import { useEffect, lazy, Suspense, useState } from 'react';
import { Routes, Route } from 'react-router-dom';
import { AlertTriangle, XCircle } from 'lucide-react';
import { useAppStore } from './store/useAppStore';
import ErrorBoundary from './components/common/ErrorBoundary';
import NavigationGuard from './components/common/NavigationGuard';
import Logger from './services/Logger';
import { startCustomerCreditAutoHealLifecycle } from './services/db/customerCreditRepository';
import Layout from './components/layout/Layout';
import WelcomeModal from './components/common/WelcomeModal';
import StaffLoginModal from './components/common/StaffLoginModal';
import AdminLoginModal from './components/common/AdminLoginModal';
import AdminEnrollmentModal from './components/common/AdminEnrollmentModal';
import LicenseAccessChooser from './components/common/LicenseAccessChooser';
import LicenseChangeRequiredModal from './components/common/LicenseChangeRequiredModal';
import LocalTenantMismatchScreen from './components/common/LocalTenantMismatchScreen';
import RenewalModal from './components/common/RenewalModal';
import SetupModal from './components/common/SetupModal';
import PermissionRoute from './components/common/PermissionRoute';
import SettingsRoute from './components/common/SettingsRoute';
import SalesReportsRoute from './components/common/SalesReportsRoute';
import CommercialAIAgentsRoute from './components/ai/CommercialAIAgentsRoute';
import EcommerceOrdersRoute from './components¶»§q«^