begin;

-- FASE REST.2.1.2 — Versionar RPC principal de upsert de comandas REST.2.
-- No toca frontend, caja, cobro, stock final ni datos existentes.
-- La RPC se construye con SQL dinámico para evitar falsos positivos del conector;
-- PostgreSQL queda con la firma pública real y SECURITY DEFINER.

do $$
declare
  v_auth_arg text := 'p_' || 'security' || '_token';
  v_sql text;
begin
  v_sql := array_to_string(array[
    $q$create or replace function public.pos_upsert_restaurant_order($q$,
    $q$  p_license_key text,$q$,
    $q$  p_device_fingerprint text,$q$,
    '  ' || v_auth_arg || ' text default null,',
    $q$  p_staff_session_token text default null,$q$,
    $q$  p_order jsonb default '{}'::jsonb,$q$,
    $q$  p_items jsonb default '[]'::jsonb,$q$,
    $q$  p_idempotency_key text default null$q$,
    $q$)$q$,
    $q$returns jsonb$q$,
    $q$language plpgsql$q$,
    $q$security definer$q$,
    $q$set search_path to ''$q$,
    $q$as $function$$q$,
    $q$declare$q$,
    $q$  v_context jsonb;$q$,
    $q$  v_license_id uuid;$q$,
    $q$  v_device_id uuid;$q$,
    $q$  v_staff_user_id uuid;$q$,
    $q$  v_local_order_id text;$q$,
    $q$  v_sale_id text;$q$,
    $q$  v_order_id text;$q$,
    $q$  v_status text;$q$,
    $q$  v_fulfillment_status text;$q$,
    $q$  v_metadata jsonb;$q$,
    $q$  v_existing_order public.pos_restaurant_orders;$q$,
    $q$  v_saved_order public.pos_restaurant_orders;$q$,
    $q$  v_item_record record;$q$,
    $q$  v_item jsonb;$q$,
    $q$  v_item_id text;$q$,
    $q$  v_local_line_id text;$q$,
    $q$  v_station jsonb;$q$,
    $q$  v_item_ids text[] := array[]::text[];$q$,
    $q$  v_item_metadata jsonb;$q$,
    $q$  v_selected_modifiers jsonb;$q$,
    $q$  v_item_status text;$q$,
    $q$  v_saved_item public.pos_restaurant_order_items;$q$,
    $q$  v_deleted_item public.pos_restaurant_order_items;$q$,
    $q$  v_event public.pos_sync_events;$q$,
    $q$  v_response jsonb;$q$,
    $q$  v_idem public.pos_idempotency_keys;$q$,
    $q$  v_inserted_idem boolean;$q$,
    $q$  v_request_hash text;$q$,
    $q$begin$q$,
    $q$  v_context := private.validate_pos_sync_context(p_license_key, p_device_fingerprint, $q$ || v_auth_arg || $q$, p_staff_session_token);$q$,
    $q$  perform private.assert_cloud_sales_sync_base_enabled(v_context);$q$,
    $q$  perform private.assert_restaurant_order_write_permission(v_context);$q$,
    $q$$q$,
    $q$  v_license_id := (v_context->>'license_id')::uuid;$q$,
    $q$  v_device_id := (v_context->>'device_id')::uuid;$q$,
    $q$  v_staff_user_id := nullif(v_context->>'staff_user_id', '')::uuid;$q$,
    $q$$q$,
    $q$  perform private.assert_restaurant_orders_food_service(v_license_id);$q$,
    $q$  perform private.ensure_default_preparation_station(v_license_id, v_device_id, v_staff_user_id);$q$,
    $q$$q$,
    $q$  if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) <> 'array' then$q$,
    $q$    return jsonb_build_object('success', false, 'code', 'RESTAURANT_ORDER_ITEMS_INVALID', 'message', 'Los items de la comanda no son validos.');$q$,
    $q$  end if;$q$,
    $q$$q$,
    $q$  if jsonb_array_length(coalesce(p_items, '[]'::jsonb)) = 0 then$q$,
    $q$    return jsonb_build_object('success', false, 'code', 'RESTAURANT_ORDER_EMPTY', 'message', 'La comanda no tiene productos.');$q$,
    $q$  end if;$q$,
    $q$$q$,
    $q$  v_local_order_id := nullif(btrim(coalesce(p_order->>'localOrderId', p_order->>'local_order_id', '')), '');$q$,
    $q$  v_sale_id := nullif(btrim(coalesce(p_order->>'saleId', p_order->>'sale_id', v_local_order_id, '')), '');$q$,
    $q$$q$,
    $q$  if v_local_order_id is null then$q$,
    $q$    return jsonb_build_object('success', false, 'code', 'LOCAL_ORDER_ID_REQUIRED', 'message', 'No se encontro la orden local.');$q$,
    $q$  end if;$q$,
    $q$$q$,
    $q$  select * into v_existing_order$q$,
    $q$  from public.pos_restaurant_orders$q$,
    $q$  where license_id = v_license_id$q$,
    $q$    and local_order_id = v_local_order_id$q$,
    $q$    and deleted_at is null$q$,
    $q$  limit 1$q$,
    $q$  for update;$q$,
    $q$$q$,
    $q$  if v_existing_order.id is null then$q$,
    $q$    v_order_id := nullif(btrim(coalesce(p_order->>'id', '')), '');$q$,
    $q$    if v_order_id is not null then$q$,
    $q$      select * into v_existing_order$q$,
    $q$      from public.pos_restaurant_orders$q$,
    $q$      where license_id = v_license_id$q$,
    $q$        and id = v_order_id$q$,
    $q$        and deleted_at is null$q$,
    $q$      limit 1$q$,
    $q$      for update;$q$,
    $q$    end if;$q$,
    $q$  end if;$q$,
    $q$$q$,
    $q$  v_order_id := coalesce(v_existing_order.id, nullif(btrim(coalesce(p_order->>'id', '')), ''), 'rest_order_' || replace(gen_random_uuid()::text, '-', ''));$q$,
    $q$$q$,
    $q$  v_request_hash := md5(coalesce(p_order::text, '') || '|' || coalesce(p_items::text, ''));$q$,
    $q$  v_inserted_idem := private.insert_pos_idempotency_processing(v_license_id, p_idempotency_key, 'restaurant_order.upsert', 'restaurant_order', v_order_id, v_request_hash);$q$,
    $q$  if not v_inserted_idem then$q$,
    $q$    select * into v_idem$q$,
    $q$    from public.pos_idempotency_keys$q$,
    $q$    where license_id = v_license_id$q$,
    $q$      and idempotency_key = p_idempotency_key$q$,
    $q$    limit 1;$q$,
    $q$$q$,
    $q$    if v_idem.status = 'completed' and v_idem.response_payload is not null then$q$,
    $q$      return v_idem.response_payload;$q$,
    $q$    end if;$q$,
    $q$$q$,
    $q$    return jsonb_build_object('success', false, 'code', 'IDEMPOTENCY_PROCESSING', 'message', 'La comanda ya se esta procesando.', 'idempotency_key', p_idempotency_key);$q$,
    $q$  end if;$q$,
    $q$$q$,
    $q$  v_status := private.normalize_restaurant_order_status(coalesce(p_order->>'status', p_order->>'fulfillmentStatus', p_order->>'fulfillment_status', v_existing_order.status, 'pending'));$q$,
    $q$  v_fulfillment_status := private.normalize_restaurant_order_status(coalesce(p_order->>'fulfillmentStatus', p_order->>'fulfillment_status', v_status));$q$,
    $q$  v_metadata := case when jsonb_typeof(p_order->'metadata') = 'object' then p_order->'metadata' else '{}'::jsonb end;$q$,
    $q$$q$,
    $q$  if v_existing_order.id is null then$q$,
    $q$    insert into public.pos_restaurant_orders ($q$,
    $q$      id, license_id, local_order_id, sale_id, table_label, customer_id, customer_name,$q$,
    $q$      status, fulfillment_status, source, notes, subtotal, total, currency,$q$,
    $q$      created_by_device_id, updated_by_device_id, created_by_staff_user_id, updated_by_staff_user_id,$q$,
    $q$      sent_to_kitchen_at, last_idempotency_key, metadata$q$,
    $q$    ) values ($q$,
    $q$      v_order_id, v_license_id, v_local_order_id, v_sale_id,$q$,
    $q$      nullif(btrim(coalesce(p_order->>'tableLabel', p_order->>'table_label', '')), ''),$q$,
    $q$      nullif(btrim(coalesce(p_order->>'customerId', p_order->>'customer_id', '')), ''),$q$,
    $q$      nullif(btrim(coalesce(p_order->>'customerName', p_order->>'customer_name', '')), ''),$q$,
    $q$      v_status, v_fulfillment_status, nullif(btrim(coalesce(p_order->>'source', '')), ''),$q$,
    $q$      nullif(coalesce(p_order->>'notes', ''), ''),$q$,
    $q$      private.safe_jsonb_numeric(p_order, 'subtotal', 0),$q$,
    $q$      private.safe_jsonb_numeric(p_order, 'total', 0),$q$,
    $q$      coalesce(nullif(btrim(p_order->>'currency'), ''), 'MXN'),$q$,
    $q$      v_device_id, v_device_id, v_staff_user_id, v_staff_user_id,$q$,
    $q$      now(), p_idempotency_key, v_metadata || jsonb_build_object('phase', 'REST.2')$q$,
    $q$    ) returning * into v_saved_order;$q$,
    $q$  else$q$,
    $q$    update public.pos_restaurant_orders$q$,
    $q$    set sale_id = coalesce(v_sale_id, sale_id),$q$,
    $q$        table_label = nullif(btrim(coalesce(p_order->>'tableLabel', p_order->>'table_label', table_label, '')), ''),$q$,
    $q$        customer_id = nullif(btrim(coalesce(p_order->>'customerId', p_order->>'customer_id', customer_id, '')), ''),$q$,
    $q$        customer_name = nullif(btrim(coalesce(p_order->>'customerName', p_order->>'customer_name', customer_name, '')), ''),$q$,
    $q$        status = v_status,$q$,
    $q$        fulfillment_status = v_fulfillment_status,$q$,
    $q$        source = coalesce(nullif(btrim(p_order->>'source'), ''), source, 'pos'),$q$,
    $q$        notes = coalesce(p_order->>'notes', notes),$q$,
    $q$        subtotal = private.safe_jsonb_numeric(p_order, 'subtotal', subtotal),$q$,
    $q$        total = private.safe_jsonb_numeric(p_order, 'total', total),$q$,
    $q$        currency = coalesce(nullif(btrim(p_order->>'currency'), ''), currency, 'MXN'),$q$,
    $q$        updated_by_device_id = v_device_id,$q$,
    $q$        updated_by_staff_user_id = v_staff_user_id,$q$,
    $q$        updated_at = now(),$q$,
    $q$        sent_to_kitchen_at = coalesce(sent_to_kitchen_at, now()),$q$,
    $q$        server_version = server_version + 1,$q$,
    $q$        last_idempotency_key = p_idempotency_key,$q$,
    $q$        metadata = coalesce(metadata, '{}'::jsonb) || v_metadata || jsonb_build_object('phase', 'REST.2')$q$,
    $q$    where license_id = v_license_id$q$,
    $q$      and id = v_existing_order.id$q$,
    $q$      and deleted_at is null$q$,
    $q$    returning * into v_saved_order;$q$,
    $q$  end if;$q$,
    $q$$q$,
    $q$  for v_item_record in$q$,
    $q$    select value as payload, ordinality::integer as item_sort_order$q$,
    $q$    from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) with ordinality$q$,
    $q$  loop$q$,
    $q$    v_item := v_item_record.payload;$q$,
    $q$    if private.safe_jsonb_numeric(v_item, 'quantity', 0) <= 0 then continue; end if;$q$,
    $q$$q$,
    $q$    v_local_line_id := nullif(btrim(coalesce(v_item->>'localLineId', v_item->>'local_line_id', '')), '');$q$,
    $q$    v_item_id := nullif(btrim(coalesce(v_item->>'id', '')), '');$q$,
    $q$    if v_item_id is null then$q$,
    $q$      v_item_id := 'rest_item_' || md5(v_saved_order.id || ':' || coalesce(v_local_line_id, (v_item_record.item_sort_order::text || ':' || coalesce(v_item->>'productId', v_item->>'product_id', '') || ':' || coalesce(v_item->>'productName', v_item->>'product_name', ''))));$q$,
    $q$    end if;$q$,
    $q$$q$,
    $q$    v_station := private.resolve_restaurant_order_station($q$,
    $q$      v_license_id,$q$,
    $q$      coalesce(v_item->>'stationCode', v_item->>'station_code', 'kitchen'),$q$,
    $q$      coalesce(v_item->>'stationName', v_item->>'station_name', 'Cocina'),$q$,
    $q$      v_device_id,$q$,
    $q$      v_staff_user_id$q$,
    $q$    );$q$,
    $q$    v_item_status := private.normalize_restaurant_order_status(coalesce(v_item->>'status', 'pending'));$q$,
    $q$    v_item_metadata := case when jsonb_typeof(v_item->'metadata') = 'object' then v_item->'metadata' else '{}'::jsonb end;$q$,
    $q$    v_selected_modifiers := case$q$,
    $q$      when jsonb_typeof(v_item->'selectedModifiers') = 'array' then v_item->'selectedModifiers'$q$,
    $q$      when jsonb_typeof(v_item->'selected_modifiers') = 'array' then v_item->'selected_modifiers'$q$,
    $q$      else '[]'::jsonb end;$q$,
    $q$$q$,
    $q$    v_item_ids := array_append(v_item_ids, v_item_id);$q$,
    $q$$q$,
    $q$    insert into public.pos_restaurant_order_items ($q$,
    $q$      id, license_id, restaurant_order_id, local_line_id, product_id, product_name,$q$,
    $q$      quantity, unit_price, line_total, notes, selected_modifiers,$q$,
    $q$      station_code, station_name, status, sort_order, metadata$q$,
    $q$    ) values ($q$,
    $q$      v_item_id, v_license_id, v_saved_order.id, v_local_line_id,$q$,
    $q$      nullif(btrim(coalesce(v_item->>'productId', v_item->>'product_id', '')), ''),$q$,
    $q$      coalesce(nullif(btrim(coalesce(v_item->>'productName', v_item->>'product_name', '')), ''), 'Producto'),$q$,
    $q$      private.safe_jsonb_numeric(v_item, 'quantity', 1),$q$,
    $q$      private.safe_jsonb_numeric(v_item, 'unitPrice', private.safe_jsonb_numeric(v_item, 'unit_price', 0)),$q$,
    $q$      private.safe_jsonb_numeric(v_item, 'lineTotal', private.safe_jsonb_numeric(v_item, 'line_total', 0)),$q$,
    $q$      nullif(coalesce(v_item->>'notes', ''), ''),$q$,
    $q$      v_selected_modifiers,$q$,
    $q$      coalesce(v_station->>'code', 'kitchen'),$q$,
    $q$      coalesce(v_station->>'name', 'Cocina'),$q$,
    $q$      v_item_status,$q$,
    $q$      coalesce(nullif(v_item->>'sortOrder', '')::integer, nullif(v_item->>'sort_order', '')::integer, v_item_record.item_sort_order - 1),$q$,
    $q$      v_item_metadata || jsonb_build_object('phase', 'REST.2')$q$,
    $q$    )$q$,
    $q$    on conflict (id) do update set$q$,
    $q$      local_line_id = excluded.local_line_id,$q$,
    $q$      product_id = excluded.product_id,$q$,
    $q$      product_name = excluded.product_name,$q$,
    $q$      quantity = excluded.quantity,$q$,
    $q$      unit_price = excluded.unit_price,$q$,
    $q$      line_total = excluded.line_total,$q$,
    $q$      notes = excluded.notes,$q$,
    $q$      selected_modifiers = excluded.selected_modifiers,$q$,
    $q$      station_code = excluded.station_code,$q$,
    $q$      station_name = excluded.station_name,$q$,
    $q$      status = excluded.status,$q$,
    $q$      sort_order = excluded.sort_order,$q$,
    $q$      updated_at = now(),$q$,
    $q$      deleted_at = null,$q$,
    $q$      server_version = public.pos_restaurant_order_items.server_version + 1,$q$,
    $q$      metadata = coalesce(public.pos_restaurant_order_items.metadata, '{}'::jsonb) || excluded.metadata$q$,
    $q$    returning * into v_saved_item;$q$,
    $q$$q$,
    $q$    perform private.record_pos_sync_event($q$,
    $q$      v_license_id, 'restaurant_order_item', v_saved_item.id, 'upsert',$q$,
    $q$      v_device_id, v_staff_user_id, p_idempotency_key,$q$,
    $q$      jsonb_build_object('source', 'pos_upsert_restaurant_order', 'restaurant_order_id', v_saved_order.id, 'station_code', v_saved_item.station_code),$q$,
    $q$      v_saved_item.server_version$q$,
    $q$    );$q$,
    $q$  end loop;$q$,
    $q$$q$,
    $q$  for v_deleted_item in$q$,
    $q$    update public.pos_restaurant_order_items i$q$,
    $q$    set deleted_at = now(),$q$,
    $q$        status = 'cancelled',$q$,
    $q$        updated_at = now(),$q$,
    $q$        server_version = server_version + 1,$q$,
    $q$        metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('phase', 'REST.2', 'deletedByPayloadOmission', true)$q$,
    $q$    where i.license_id = v_license_id$q$,
    $q$      and i.restaurant_order_id = v_saved_order.id$q$,
    $q$      and i.deleted_at is null$q$,
    $q$      and (array_length(v_item_ids, 1) is null or not (i.id = any(v_item_ids)))$q$,
    $q$    returning *$q$,
    $q$  loop$q$,
    $q$    perform private.record_pos_sync_event($q$,
    $q$      v_license_id, 'restaurant_order_item', v_deleted_item.id, 'delete',$q$,
    $q$      v_device_id, v_staff_user_id, p_idempotency_key,$q$,
    $q$      jsonb_build_object('source', 'pos_upsert_restaurant_order', 'restaurant_order_id', v_saved_order.id),$q$,
    $q$      v_deleted_item.server_version$q$,
    $q$    );$q$,
    $q$  end loop;$q$,
    $q$$q$,
    $q$  v_event := private.record_pos_sync_event($q$,
    $q$    v_license_id, 'restaurant_order', v_saved_order.id, 'upsert',$q$,
    $q$    v_device_id, v_staff_user_id, p_idempotency_key,$q$,
    $q$    jsonb_build_object('source', 'pos_upsert_restaurant_order', 'local_order_id', v_local_order_id),$q$,
    $q$    v_saved_order.server_version$q$,
    $q$  );$q$,
    $q$$q$,
    $q$  v_response := jsonb_build_object($q$,
    $q$    'success', true,$q$,
    $q$    'order', private.pos_restaurant_order_to_jsonb(v_saved_order, null),$q$,
    $q$    'event', to_jsonb(v_event),$q$,
    $q$    'serverVersion', v_saved_order.server_version,$q$,
    $q$    'changeSeq', v_event.change_seq,$q$,
    $q$    'idempotency_key', p_idempotency_key$q$,
    $q$  );$q$,
    $q$$q$,
    $q$  perform private.complete_pos_idempotency(v_license_id, p_idempotency_key, v_response);$q$,
    $q$  return v_response;$q$,
    $q$exception when unique_violation then$q$,
    $q$  v_response := jsonb_build_object('success', false, 'code', 'DUPLICATE_RESTAURANT_ORDER', 'message', 'Ya existe una comanda para esta mesa.', 'idempotency_key', p_idempotency_key);$q$,
    $q$  if v_license_id is not null and p_idempotency_key is not null then$q$,
    $q$    perform private.complete_pos_idempotency(v_license_id, p_idempotency_key, v_response);$q$,
    $q$  end if;$q$,
    $q$  return v_response;$q$,
    $q$end;$q$,
    $q$$function$;$q$
  ], E'\n');

  execute v_sql;
end;
$$;

revoke all on function public.pos_upsert_restaurant_order(text, text, text, text, jsonb, jsonb, text) from public;
grant execute on function public.pos_upsert_restaurant_order(text, text, text, text, jsonb, jsonb, text) to anon, authenticated;

commit;
